default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: catalog-backend_development

staging:
  <<: *default
  database: catalog-backend_staging

test:
  <<: *default
  database: catalog-backend_test
